export const months = [
  {
    english: "January",
    nominative: "leden",
    locative: "lednu",
    genitive: "ledna",
  },
  {
    english: "February",
    nominative: "únor",
    locative: "únoru",
    genitive: "února",
  },
  {
    english: "March",
    nominative: "březen",
    locative: "březnu",
    genitive: "března",
  },
  {
    english: "April",
    nominative: "duben",
    locative: "dubnu",
    genitive: "dubna",
  },
  {
    english: "May",
    nominative: "květen",
    locative: "květnu",
    genitive: "května",
  },
  {
    english: "June",
    nominative: "červen",
    locative: "červnu",
    genitive: "června",
  },
  {
    english: "July",
    nominative: "červenec",
    locative: "červenci",
    genitive: "července",
  },
  {
    english: "August",
    nominative: "srpen",
    locative: "srpnu",
    genitive: "srpna",
  },
  {
    english: "September",
    nominative: "září",
    locative: "září",
    genitive: "září",
  },
  {
    english: "October",
    nominative: "říjen",
    locative: "říjnu",
    genitive: "října",
  },
  {
    english: "November",
    nominative: "listopad",
    locative: "listopadu",
    genitive: "listopadu",
  },
  {
    english: "December",
    nominative: "prosinec",
    locative: "prosinci",
    genitive: "prosince",
  },
];

export const ordinalGenitive = {
  1: "prvního",
  2: "druhého",
  3: "třetího",
  4: "čtvrtého",
  5: "pátého",
  6: "šestého",
  7: "sedmého",
  8: "osmého",
  9: "devátého",
  10: "desátého",
  11: "jedenáctého",
  12: "dvanáctého",
  13: "třináctého",
  14: "čtrnáctého",
  15: "patnáctého",
  16: "šestnáctého",
  17: "sedmnáctého",
  18: "osmnáctého",
  19: "devatenáctého",
  20: "dvacátého",
  21: "dvacátého prvního",
  22: "dvacátého druhého",
  23: "dvacátého třetího",
  24: "dvacátého čtvrtého",
  25: "dvacátého pátého",
  26: "dvacátého šestého",
  27: "dvacátého sedmého",
  28: "dvacátého osmého",
  29: "dvacátého devátého",
  30: "třicátého",
  31: "třicátého prvního",
};
